### ISSUE TITLE
ERROR: (gcloud.config.set) The project property must be set to a valid project ID, [$PROJECT_ID] is not a valid project ID.

### ISSUE THREAD

**Issue by kaihendry** [google-github-actions/setup-gcloud#253]
### Question

I'm using https://github.com/google-github-actions/setup-gcloud/blob/master/example-workflows/cloud-run/.github/workflows/cloud-run.yml#L41

I don't understand why you used `project_id: ${{ secrets.RUN_PROJECT }}` instead of `project_id: "$PROJECT_ID"`?

Nonetheless I don't understand why I am hitting this error:
https://github.com/kaihendry/count/runs/1588372544?check_suite_focus=true

**Comment by averikitsch** [comment]
Hi @kaihendry , unfortunately due to limitations of GitHub Actions actions can not accept environment variables as inputs in the form of `$PROJECT_ID`. However, you can use the `${{ }}` format to pass in variables to actions. I would recommend using either `${{ secrets.RUN_PROJECT }}` or `${{ env.PROJECT_ID }}`.

**Comment by kaihendry** [comment]
Thanks! https://github.com/kaihendry/count/commit/d96332f1cea623a0904dff5a28f737e57f887114

I wonder if the `          version: '290.0.1'` is required?

**Comment by bharathkkb** [comment]
@kaihendry by default if you do not specify `version`, it will pull latest version of gcloud. 
If you wish to pin to a specific gcloud version for any reason, then you can do so by `version: `.
