### ISSUE TITLE
Error when using setup-gcloud action on some windows self-hosted runners

### ISSUE THREAD

**Issue by uportalis** [google-github-actions/setup-gcloud#401]
### TL;DR

I get an error when using setup-gcloud action on some self-hosted runners since merge of PR #397

**Expected behavior**

I expect that setup-gcloud actin performs without error

**Observed behavior**

I get the following error:
```
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "$ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; if ((Get-Command -Name Expand-Archive -Module Microsoft.PowerShell.Archive -ErrorAction Ignore)) { Expand-Archive -LiteralPath 'D:\actions-runner\_work\_temp\4dd3c246-c3e8-4095-b02c-dbbe4e13f759' -DestinationPath 'D:\actions-runner\_work\_temp\d184887a-f2b0-459e-9541-d371dfbb6ce4' -Force } else {[System.IO.Compression.ZipFile]::ExtractToDirectory('D:\actions-runner\_work\_temp\4dd3c246-c3e8-4095-b02c-dbbe4e13f759', 'D:\actions-runner\_work\_temp\d184887a-f2b0-459e-9541-d371dfbb6ce4', $true) }"
Cannot convert argument "entryNameEncoding", with value: "True", for 
"ExtractToDirectory" to type "System.Text.Encoding": "Cannot convert value 
"True" to type "System.Text.Encoding". Error: "Invalid cast from 
'System.Boolean' to 'System.Text.Encoding'.""
At line:1 char:408
+ $ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName 
System.IO.Compres ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordE 
   xception
    + FullyQualifiedErrorId : MethodArgumentConversionInvalidCastArgument
 
Error: 'setup-gcloud' failed to be installed: The process 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe' failed with exit code 1
```

### Reproduction

**Action YAML**

```yaml
      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_email: ${{ secrets.MY_EMAIL }}
          service_account_key: ${{ secrets.MY_KEY }}
```

**Additional information**

I'm using a self-hosted runner with:
* actions-runner v2.284.0
* Microsoft .NET Framework 4.7.2

Here are additional info:

```
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      3.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.2.9200.16398
PSCompatibleVersions           {1.0, 2.0, 3.0}
PSRemotingProtocolVersion      2.2


C:\>systeminfo

Host Name:                 HOSTNAME01
OS Name:                   Microsoft Windows 7 Professional
OS Version:                6.1.7601 Service Pack 1 Build 7601
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          admin
Registered Organization:
Product ID:                55041-033-8016497-86204
Original Install Date:     13.11.2014, 16:57:22
System Boot Time:          25.10.2021, 10:51:19
System Manufacturer:       VMware, Inc.
System Model:              VMware Virtual Platform
System Type:               x64-based PC
Processor(s):              2 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 79 Stepping 1 GenuineIntel ~2100 Mhz
                           [02]: Intel64 Family 6 Model 79 Stepping 1 GenuineIntel ~2100 Mhz
BIOS Version:              Phoenix Technologies LTD 6.00, 12.12.2018
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              fr-ch;French (Switzerland)
Time Zone:                 (UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna
Total Physical Memory:     4'095 MB
Available Physical Memory: 2'591 MB
Virtual Memory: Max Size:  8'189 MB
Virtual Memory: Available: 6'261 MB
Virtual Memory: In Use:    1'928 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\HOSTNAME01
Hotfix(s):                 309 Hotfix(s) Installed.
```

**Comment by uportalis** [comment]
I know, I should probably stop using Windows 7 😞 
But it still is in the list of supported OS for self-hosted runners: https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners#supported-architectures-and-operating-systems-for-self-hosted-runners

**Comment by bharathkkb** [comment]
@uportalis Thanks for the report! Does this fail at `setup-gcloud` setup job or during workflow?

**Comment by uportalis** [comment]
I got the same error on a VM running Windows 10.
So this is not related to Windows 7.

```
PS C:\Users\Administrator> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.1320
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1320
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


PS C:\Users\Administrator> systeminfo

Host Name:                 HOSTNAME02
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19042 N/A Build 19042
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          Admin
Registered Organization:
Product ID:                00330-80000-00000-AA412
Original Install Date:     03/05/2021, 11:13:42
System Boot Time:          18/11/2021, 07:34:52
System Manufacturer:       VMware, Inc.
System Model:              VMware7,1
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: AMD64 Family 23 Model 49 Stepping 0 AuthenticAMD ~2795 Mhz
BIOS Version:              VMware, Inc. VMW71.00V.13989454.B64.1906190538, 19/06/2019
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume2
System Locale:             en-gb;English (United Kingdom)
Input Locale:              fr-ch;French (Switzerland)
Time Zone:                 (UTC+00:00) Dublin, Edinburgh, Lisbon, London
Total Physical Memory:     8.191 MB
Available Physical Memory: 4.106 MB
Virtual Memory: Max Size:  9.471 MB
Virtual Memory: Available: 3.408 MB
Virtual Memory: In Use:    6.063 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\HOSTNAME02
[...]
```

Does anyone have any idea what is causing this problem?

**Comment by sethvargo** [comment]
What version of the actions runner? I'm skeptical this is a result of #397 and more likely a result of updating to the latest `actions/tool-cache` package. The error seems to be coming from calling `ExtractToDirectory`, which is not something our SDK calls directly. I think `actions/tool-cache` calls this in `extractZipWin`: https://github.com/actions/toolkit/blob/a1b068ec31a042ff1e10a522d8fdf0b8869d53ca/packages/tool-cache/src/tool-cache.ts#L352

**Comment by uportalis** [comment]
I'm using this version of the GitHub runner: 2.285.1
Using `google-github-actions/setup-gcloud@e647fdc963db695d93c2ec13e65fd4acc2471ec3` instead of `google-github-actions/setup-gcloud@master` works fine.

**Comment by uportalis** [comment]
FYI, I have a scheduled workflow that deletes the content of `_work/_tool/` when it gets too big. But is does not touch the `_work/_temp/` folder.
I don't know if that would be causing a problem with the way the setup-gcloud action downloads and extracts gcloud SDK.

**Comment by sethvargo** [comment]
I did some more digging, and I'm pretty sure this is an `actions/tool-cache` bug and/or no longer supported by GitHub Actions due to Windows 7. `ExtractToDirectory` has [four possible signatures](https://docs.microsoft.com/en-us/dotnet/api/system.io.compression.zipfile.extracttodirectory?view=net-6.0):

1. `ExtractToDirectory(String, String)`
2. `ExtractToDirectory(String, String, Boolean)`
3. `ExtractToDirectory(String, String, Encoding)`
4. `ExtractToDirectory(String, String, Encoding, Boolean)`

actions/tool-cache is attempting to call the `String, String, Boolean` version (https://github.com/actions/toolkit/blob/a1b068ec31a042ff1e10a522d8fdf0b8869d53ca/packages/tool-cache/src/tool-cache.ts#L374-L395), but that does not seem to be defined on the version of Windows 7 that you're running.

From reading the actions/tool-cache code, it also looks like GitHub Actions [prefers `pwsh` over `powershell`](https://github.com/actions/toolkit/blob/a1b068ec31a042ff1e10a522d8fdf0b8869d53ca/packages/tool-cache/src/tool-cache.ts#L348-L353) so perhaps installing or upgrading `pwsh` might help.

This behavior was changed/introduced in https://github.com/actions/toolkit/commit/a1b068ec31a042ff1e10a522d8fdf0b8869d53ca#diff-725a5ef102ee3762738a5500c3d7c5b6afef874a1cb67c55085ad5e4615b1a6f (May 21, 2021), which was included in the version of actions/tool-cache we recently updated to. You can actually see in the diff where the [old command](https://github.com/actions/toolkit/commit/a1b068ec31a042ff1e10a522d8fdf0b8869d53ca#diff-725a5ef102ee3762738a5500c3d7c5b6afef874a1cb67c55085ad5e4615b1a6fL347) only used the two-argument signature:

```powershell
ExtractToDirectory('${escapedFile}', '${escapedDest}')
```

The diff shows the introduction of the third parameter, which does not seem to be accepted by your version of Powershell. Specifying a third boolean indicates "overwrite files", but it seems to be only new newer .NET releases. 

Since this is happening in actions/tool-cache, I don't think there's much we can do. We also can't downgrade because there's a security patch in the latest release. Here's my suggestions:

1. Try upgrading the .NET version to 5.0 or 6.0 on your Windows 7 machines
2. Try installing/upgrading `pwsh`
3. File an issue on actions/tool-cache (although I suspect they'll simply close with "Windows 7 is not supported")

Since there's nothing we can do to fix this in the setup-gcloud action, I'm going to close out this issue. I've linked above to the exact LOC in actions/tool-cache where the invalid command is running, and recommended some possible mitigations above. Sorry!
