### ISSUE TITLE
NodeJS 18x

### ISSUE THREAD

**Issue by noelbranz** [google-github-actions/setup-gcloud#614]
### TL;DR

Support for NodeJS 18

**Comment by sethvargo** [comment]
Is this related to https://github.com/actions/runner-images/issues/7002?

**Comment by noelbranz** [comment]
Yes but also I am using Google App Engine which Node.js 18 is now generally available.  
Which requires my app to be in NodeJS 18 engine, before it can be deployed to Nodejs18 env in GAE
I am currently using the Nodejs inside the setup-gcloud action 
Or if there is a way to specify the nodejs version env parameter to be included while using the action

**Comment by sethvargo** [comment]
I'm not sure I understand. You should be able to build your app with node 18 - it's independent of what version setup-gcloud uses to install the gcloud CLI.

We usually don't update right away, since the self-hosted runners tend to lag behind a bit more. But again, the version you need to deploy your GAE app is independent of the version setup-gcloud uses.

**Comment by noelbranz** [comment]
Thanks. maybe the link you provided is what I need to wait.

Thanks again.

**Comment by sethvargo** [comment]
Hi @noelbranz 

You don't need to wait - you can use `actions/setup-node` to install Node 18 today.

**Comment by noelbranz** [comment]
Yeah, I will try that. Thank you very much!  @sethvargo
